/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    ConversionSettings: typeof import('./src/components/processing/ConversionSettings.vue')['default']
    FileUpload: typeof import('./src/components/upload/FileUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/common/StatsCard.vue')['default']
    TaskItem: typeof import('./src/components/processing/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/processing/TaskList.vue')['default']
  }
}
